gencode_version: '35'
tx: 'gencode.v35.pc_transcripts.fa.gz'
genome: 'GRCh38.p13.genome.fa.gz'
ftp: 'rsync://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_'
annotation_path: '/data/mcgaugheyd/genomes/GRCh38/'
sample_fastq_table: 'sample_table.tsv'
forward_suffix: '_R1_001'
reverse_suffix: '_R2_001'
fastq_relative_dir: 'fastq'
star: 'True'
