sample_fastq_table: 'sample_table.tsv'
fq1_suffix: "_R1_001.fastq.gz"
fq2_suffix: "_R2_001.fastq.gz"
fqS_suffix: '.fastq.gz'
fastq_dir: "/data/mcgaugheyd/projects/nei/OGVFB_rna_seq/fastq"
star: True
counts: True
make_counts_script: '~/git/OGVFB_RNAseq/src/make_bulk_counts.R'
bigwig: True
kinship: False
hipstr: False
references:
  human:
    annotation_path: "/data/mcgaugheyd/genomes/GRCh38/"
    genome: "GRCh38.primary_assembly.genome.fa.gz"
    genome_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/GRCh38.primary_assembly.genome.fa.gz"
    gtf: "gencode.v47.annotation.gtf.gz"
    gtf_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/gencode.v47.annotation.gtf.gz"
    transcripts: "gencode.v47.transcripts.fa.gz"
    transcripts_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_47/gencode.v47.transcripts.fa.gz"
    str_regions: "/data/mcgaugheyd/genomes/GRCh38/hg38.hipstr_reference.bed"
  mouse:
    annotation_path: "/data/mcgaugheyd/genomes/GRCm39/"
    genome: "GRCm39.primary_assembly.genome.fa.gz"
    genome_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M38/GRCm39.primary_assembly.genome.fa.gz"
    gtf: "gencode.vM38.annotation.gtf.gz"
    gtf_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M38/gencode.vM38.annotation.gtf.gz"
    transcripts: "gencode.vM38.transcripts.fa.gz"
    transcripts_url: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M38/gencode.vM38.transcripts.fa.gz"
  zebrafish:
    annotation_path: "/data/mcgaugheyd/genomes/GRCz11/"
    genome: "Danio_rerio.GRCz11.dna.primary_assembly.fa.gz"
    genome_url: "ftp://ftp.ensembl.org/pub/release-115/fasta/danio_rerio/dna/Danio_rerio.GRCz11.dna.primary_assembly.fa.gz"
    gtf: "Danio_rerio.GRCz11.115.gtf.gz"
    gtf_url: "ftp://ftp.ensembl.org/pub/release-115/gtf/danio_rerio/Danio_rerio.GRCz11.115.gtf.gz"
    transcripts: "Danio_rerio.GRCz11.cdna.all.fa.gz"
    transcripts_url: "ftp://ftp.ensembl.org/pub/release-115/fasta/danio_rerio/cdna/Danio_rerio.GRCz11.cdna.all.fa.gz"
  rat:
    annotation_path: "/data/mcgaugheyd/genomes/GRCr8/"
    genome: "Rattus_norvegicus.GRCr8.dna.toplevel.fa.gz"
    genome_url: "ftp://ftp.ensembl.org/pub/release-115/fasta/rattus_norvegicus/dna/Rattus_norvegicus.GRCr8.dna.toplevel.fa.gz"
    gtf: "Rattus_norvegicus.GRCr8.115.gtf.gz"
    gtf_url: "ftp://ftp.ensembl.org/pub/release-115/gtf/rattus_norvegicus/Rattus_norvegicus.GRCr8.115.gtf.gz"
    transcripts: "Rattus_norvegicus.GRCr8.cdna.all.fa.gz"
    transcripts_url: "ftp://ftp.ensembl.org/pub/release-115/fasta/rattus_norvegicus/cdna/Rattus_norvegicus.GRCr8.cdna.all.fa.gz" 
